
DROP TABLE ECOM_DWH.RAW.RAW_USERS;

UNDROP TABLE ECOM_DWH.RAW.RAW_USERS;

DELETE FROM ECOM_DWH.MART.FACT_ORDER 
WHERE quantity > 0;

INSERT INTO ECOM_DWH.MART.FACT_ORDER 
SELECT * FROM ECOM_DWH.MART.FACT_ORDER AT(OFFSET => -60 * 5) 
WHERE quantity > 0;