CREATE STREAM ECOM_DWH.RAW.STREAM_RAW_USERS    ON TABLE ECOM_DWH.RAW.RAW_USERS;
CREATE STREAM ECOM_DWH.RAW.STREAM_RAW_PRODUCTS ON TABLE ECOM_DWH.RAW.RAW_PRODUCTS;
CREATE STREAM ECOM_DWH.RAW.STREAM_RAW_ORDERS   ON TABLE ECOM_DWH.RAW.RAW_ORDERS;
CREATE STREAM ECOM_DWH.CLEANED.STREAM_INT_ORDERS ON TABLE ECOM_DWH.CLEANED.INT_ORDERS;
CREATE STREAM ECOM_DWH.CLEANED.STREAM_INT_USERS    ON TABLE ECOM_DWH.CLEANED.INT_USERS;
CREATE STREAM ECOM_DWH.CLEANED.STREAM_INT_PRODUCTS ON TABLE ECOM_DWH.CLEANED.INT_PRODUCTS;